### ISSUE TITLE
nda muncul gambar di hasil pencarian, mar di admin so ada gambar

### ISSUE THREAD

**Issue by SoundsKiller** [stannyc/orens_issues#8]
![WhatsApp Image 2021-08-31 at 10 59 04 PM](https://user-images.githubusercontent.com/89591667/131529020-293bb4e0-6644-41b6-ac15-0199b18bdf62.jpeg)
![WhatsApp Image 2021-08-31 at 11 12 30 PM](https://user-images.githubusercontent.com/89591667/131529035-6250e7ae-2112-4a27-b2d0-9b37109c730f.jpeg)

**Comment by stannyc** [comment]
User  a NOT wooden phone,  with a NOT shitty internet connection... :
